name: 'PR Cherry Pick'
description:
    'Cherry-picks commits from a merged PR, creating a new PR to a target branch'
author: 'wireapp'

branding:
    icon: 'copy'
    color: 'purple'

inputs:
    target-branch:
        description: 'Name of the branch that cherry-pick PRs should target'
        required: true
    pr-creator-token:
        description:
            'Personal Access Token used to create the PR. Uses default actions
            token by default.'
        required: false
        default: ${{ github.token }}
    submodules-target-branch:
        description: >
            (optional) target branch for submodules. If set, the action will try
            to fast-forward all submodules to the newest version possible of
            this specified branch.
        required: false
        default: ''
    pr-assignee:
        description:
            '(optional) User ID to be assigned to the created PR. Will use the
            assignee of the original PR by default'
        required: false
        default: ''
    pr-labels:
        description:
            'Comma-separated list of labels to add to this PR. Empty by default'
        required: false
        default: ''
    pr-title-suffix:
        description:
            '(optional) suffix to be added to the title of the created PR.
            [Cherry-Pick] by default'
        required: false
        default: '[Cherry-Pick]'

outputs:
    pr-number:
        description: 'The number of the created PR'

runs:
    using: node20
    main: dist/index.js
