name: 'PR Cherry Pick'
description:
    'Cherry-picks commits from a merged PR, creating a new PR to a target branch'
author: 'wireapp'

branding:
    icon: 'copy'
    color: 'purple'

inputs:
    target-branch:
        description: 'Name of the branch that cherry-pick PRs should target'
        required: true
    pr-creator-token:
        description:
            'Personal Access Token used to create the PR. Uses default actions
            token by default.'
        required: false
        default: ${{ github.token }}
    submodule-name:
        description: >
            Optional submodule name. If set, the action will try to fast-forward
            the submodule to the newest version possible, assuming it also has a
            branch with the same target-branch.
        required: false
        default: ''
    pr-assignee:
        description:
            '(optional) User ID to be assigned to the created PR. Will use the
            author of the original PR by default'
        required: false
        default: ''
    pr-labels:
        description:
            'Comma-separated list of labels to add to this PR. Empty by default'
        required: false
        default: ''

outputs:
    pr-number:
        description: 'The number of the created PR'

runs:
    using: node20
    main: dist/index.js
